function export_coefficients_to_c(b_bp, b_notch, a_notch, Fs, F0_mains, out_path)
% EXPORT_COEFFICIENTS_TO_C  Writes a self-contained C header with the
% FIR and IIR coefficients that the ESP32 firmware #includes.
%
%   Generates a file safe to drop into firmware/esp32_ecg/.
%   The header uses PROGMEM-friendly const float arrays.

    [out_dir, ~, ~] = fileparts(out_path);
    if ~isempty(out_dir) && ~exist(out_dir, 'dir')
        mkdir(out_dir);
    end

    fid = fopen(out_path, 'w');
    if fid < 0
        error('Could not open %s for writing.', out_path);
    end

    fprintf(fid, '// ============================================================\n');
    fprintf(fid, '//  filter_coefficients.h\n');
    fprintf(fid, '//  AUTO-GENERATED by matlab/generate_coefficients.m\n');
    fprintf(fid, '//  DO NOT EDIT BY HAND - re-run the MATLAB script instead.\n');
    fprintf(fid, '//\n');
    fprintf(fid, '//  Generated: %s\n', datestr(now));
    fprintf(fid, '//  Fs       : %d Hz\n', Fs);
    fprintf(fid, '//  Notch f0 : %d Hz\n', F0_mains);
    fprintf(fid, '// ============================================================\n');
    fprintf(fid, '#ifndef FILTER_COEFFICIENTS_H\n');
    fprintf(fid, '#define FILTER_COEFFICIENTS_H\n\n');

    fprintf(fid, '#define SAMPLE_RATE_HZ   %d\n', Fs);
    fprintf(fid, '#define MAINS_FREQ_HZ    %d\n\n', F0_mains);

    % --- FIR Bandpass ------------------------------------------------
    Nbp = length(b_bp);
    fprintf(fid, '// FIR Bandpass: 0.5 Hz - 40 Hz, Hamming window, linear phase\n');
    fprintf(fid, '#define FIR_BP_LEN  %d\n', Nbp);
    fprintf(fid, 'const float FIR_BP_COEFFS[FIR_BP_LEN] = {\n');
    for k = 1:Nbp
        if mod(k - 1, 5) == 0, fprintf(fid, '    '); end
        if k < Nbp
            fprintf(fid, '%+.10ff, ', b_bp(k));
        else
            fprintf(fid, '%+.10ff\n', b_bp(k));
        end
        if mod(k, 5) == 0 && k < Nbp, fprintf(fid, '\n'); end
    end
    fprintf(fid, '};\n\n');

    % --- IIR Notch ---------------------------------------------------
    fprintf(fid, '// IIR Notch: second-order biquad @ %d Hz\n', F0_mains);
    fprintf(fid, '// Direct Form II: y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2]\n');
    fprintf(fid, '//                     - a1*y[n-1] - a2*y[n-2]\n');
    fprintf(fid, 'const float IIR_NOTCH_B[3] = {%+.10ff, %+.10ff, %+.10ff};\n', ...
            b_notch(1), b_notch(2), b_notch(3));
    fprintf(fid, 'const float IIR_NOTCH_A[3] = {%+.10ff, %+.10ff, %+.10ff};\n\n', ...
            a_notch(1), a_notch(2), a_notch(3));

    fprintf(fid, '#endif // FILTER_COEFFICIENTS_H\n');
    fclose(fid);
end
