/* ============================================================
 *  esp32_ecg.ino
 *  Real-time ECG acquisition + filtering + arrhythmia detection
 *  for the ESP32 (Doit DevKit V1) + AD8232 single-lead front end.
 *
 *  Pipeline (per sample, every ~1 ms):
 *      ADC read -> DC remove -> IIR notch (50 Hz)
 *                            -> FIR bandpass (0.5-40 Hz)
 *                            -> rectify + short integration (envelope)
 *                            -> threshold peak detect -> R-R -> BPM
 *                            -> arrhythmia classification
 *
 *  Course : Digital Signal Processing (BEC502)
 *  Project: Heart Signals and Arrhythmia Detection
 * ============================================================ */

#include "config.h"
#include "filter_coefficients.h"   // auto-generated by MATLAB

// -------- Filter state -------------------------------------------------
// 1st-order IIR DC-blocker:  y[n] = x[n] - x[n-1] + alpha * y[n-1]
// Together with the FIR bandpass below this forms the "0.5 Hz - 40 Hz
// bandpass" from the project report. The DC-blocker handles the
// low-frequency edge (baseline wander, respiration) without burning
// thousands of FIR taps; the FIR handles the 40 Hz upper edge with
// linear phase across the diagnostic ECG band.
static float dc_prev_x = 0.0f;
static float dc_prev_y = 0.0f;

// FIR circular buffer for the bandpass.
// Using a ring buffer lets us avoid memmove() every sample - we just
// advance an index and wrap around with modulo.
static float fir_buf[FIR_BP_LEN] = {0};
static int   fir_idx = 0;

// IIR notch state (Direct Form II Transposed - two delay registers)
static float notch_x1 = 0, notch_x2 = 0;
static float notch_y1 = 0, notch_y2 = 0;

// Envelope integrator (short moving sum of |filtered|)
#define ENV_WIN 16
static float env_buf[ENV_WIN] = {0};
static int   env_idx = 0;
static float env_sum = 0;

// -------- Peak detection state ----------------------------------------
static unsigned long lastPeakMs   = 0;
static unsigned long lastRR_ms    = 0;
static bool          aboveThresh  = false;
static unsigned long lastReportMs = 0;

// -------- BPM moving average (size 500 per project spec) --------------
#define BPM_BUF_SIZE 500
static float bpm_buf[BPM_BUF_SIZE] = {0};
static int   bpm_idx               = 0;
static int   bpm_count             = 0;   // number of valid entries
static float bpm_running_sum       = 0;

// =====================================================================
//  setup
// =====================================================================
void setup() {
    Serial.begin(SERIAL_BAUD);

    // AD8232 leads-off detection pins are open-drain digital outputs.
    // Pull-ups keep them HIGH unless the lead is on the body.
    pinMode(PIN_LO_PLUS,  INPUT);
    pinMode(PIN_LO_MINUS, INPUT);

    // ESP32 ADC: 12-bit (0..4095), 11 dB attenuation -> 0..~3.3 V range
    analogReadResolution(12);
    analogSetAttenuation(ADC_11db);

    // Banner so the host knows the firmware is alive.
    Serial.println(F("# ECG firmware ready"));
    Serial.print  (F("# Fs target = "));
    Serial.print  (SAMPLE_RATE_HZ);
    Serial.println(F(" Hz"));
}

// =====================================================================
//  loop  - runs once per sample
// =====================================================================
void loop() {
    // --- 1. Leads-off detection --------------------------------------
    // If either electrode is disconnected the AD8232 floats and the ADC
    // saturates. Bail out early so we don't pollute the filter history
    // with garbage values.
    if (digitalRead(PIN_LO_PLUS) == HIGH || digitalRead(PIN_LO_MINUS) == HIGH) {
        Serial.println('!');               // sentinel for the host plotter
        delay(LOOP_DELAY_MS);
        return;
    }

    // --- 2. Sample + DC remove ---------------------------------------
    // ADC_CENTER was *the* gotcha during bring-up. The first iteration
    // had the signal saturating around 3800 because the leads-off pins
    // were miswired and the AD8232 was floating high. After the wiring
    // fix the signal correctly centers near 2048 (mid-rail).
    int   raw      = analogRead(PIN_ECG);
    float centered = (float)(raw - ADC_CENTER);

    // --- 3a. DC blocker (1st-order IIR HP @ 0.5 Hz) ------------------
    //   y[n] = x[n] - x[n-1] + alpha * y[n-1]
    // Removes baseline wander and any residual ADC bias. Alpha is
    // chosen for fc = 0.5 Hz at Fs = 250 Hz, see config.h.
    float dc_out = centered - dc_prev_x + DC_BLOCK_ALPHA * dc_prev_y;
    dc_prev_x    = centered;
    dc_prev_y    = dc_out;

    // --- 3b. IIR notch (50 Hz mains) ---------------------------------
    // Second-order biquad, Direct Form II:
    //   y[n] = b0*x[n] + b1*x[n-1] + b2*x[n-2]
    //              - a1*y[n-1] - a2*y[n-2]
    float x0 = dc_out;
    float y0 = IIR_NOTCH_B[0] * x0
             + IIR_NOTCH_B[1] * notch_x1
             + IIR_NOTCH_B[2] * notch_x2
             - IIR_NOTCH_A[1] * notch_y1
             - IIR_NOTCH_A[2] * notch_y2;
    notch_x2 = notch_x1; notch_x1 = x0;
    notch_y2 = notch_y1; notch_y1 = y0;

    // --- 4. FIR bandpass via circular convolution --------------------
    // We don't shift the buffer every sample (expensive); instead we
    // overwrite the oldest tap and step through the ring from there.
    fir_buf[fir_idx] = y0;
    float bp = 0.0f;
    int   k  = fir_idx;
    for (int i = 0; i < FIR_BP_LEN; i++) {
        bp += FIR_BP_COEFFS[i] * fir_buf[k];
        k--;
        if (k < 0) k = FIR_BP_LEN - 1;
    }
    fir_idx = (fir_idx + 1) % FIR_BP_LEN;

    // --- 5. Envelope (rectify + short moving sum) --------------------
    // This is what makes the displayed waveform sit at a small positive
    // baseline with sharper "bumps" at the QRS - matches Figure 1 in
    // the report where the noise floor was at ~40 and R-peaks at ~43.
    // The constant SIG_SCALE maps the integrator output into that
    // range so the project's measured PEAK_THRESHOLD of 41.5 holds.
    float rect = fabsf(bp);
    env_sum  -= env_buf[env_idx];
    env_buf[env_idx] = rect;
    env_sum  += rect;
    env_idx   = (env_idx + 1) % ENV_WIN;

    float envelope = env_sum / (float)ENV_WIN;
    float plotVal  = ENV_BASELINE + envelope / SIG_SCALE;   // for plotting

    // --- 6. R-peak detection (rising-edge threshold cross) -----------
    unsigned long now = millis();
    if (!aboveThresh && plotVal > PEAK_THRESHOLD) {
        aboveThresh = true;

        if (lastPeakMs != 0) {
            unsigned long rr = now - lastPeakMs;

            // Physiological RR sanity gate (~30..200 BPM).
            // Rejects double-counted peaks and obvious motion artifacts.
            if (rr > RR_MIN_MS && rr < RR_MAX_MS) {
                float instBpm = 60000.0f / (float)rr;
                pushBpm(instBpm);
                classifyAndReport(instBpm, rr);
                lastRR_ms = rr;
            }
        }
        lastPeakMs = now;
    }
    else if (aboveThresh && plotVal < (PEAK_THRESHOLD - HYSTERESIS)) {
        // Hysteresis: don't re-arm until we've clearly fallen below the
        // threshold. Otherwise small wobbles on top of an R-peak count
        // as multiple beats.
        aboveThresh = false;
    }

    // --- 7. Stream filtered value to the host ------------------------
    // The Arduino Serial Plotter / Processing sketch reads one float
    // per line. Keep the format simple.
    Serial.println(plotVal, 2);

    // --- 8. Periodic BPM heartbeat for the Serial Monitor ------------
    if (now - lastReportMs > 1000) {
        lastReportMs = now;
        if (bpm_count > 0) {
            float avg = bpm_running_sum / (float)bpm_count;
            Serial.print(F("# AVG_BPM="));
            Serial.println(avg, 1);
        }
    }

    // Project spec: delay(1) prevents Serial buffer saturation while
    // keeping enough samples/sec to capture the sharp QRS upslope.
    delay(LOOP_DELAY_MS);
}

// =====================================================================
//  pushBpm - update the 500-sample moving average ring
// =====================================================================
void pushBpm(float bpm) {
    if (bpm_count < BPM_BUF_SIZE) {
        bpm_buf[bpm_idx] = bpm;
        bpm_running_sum += bpm;
        bpm_count++;
    } else {
        bpm_running_sum -= bpm_buf[bpm_idx];
        bpm_buf[bpm_idx] = bpm;
        bpm_running_sum += bpm;
    }
    bpm_idx = (bpm_idx + 1) % BPM_BUF_SIZE;
}

// =====================================================================
//  classifyAndReport - heart-rate based arrhythmia decision
// =====================================================================
//  Tachycardia : > 100 BPM
//  Bradycardia : <  60 BPM
//  Irregular   : |delta RR| / prevRR > 20%  (a beat-to-beat anomaly)
//  Normal      : otherwise (60..100 BPM, stable rhythm)
// =====================================================================
void classifyAndReport(float bpm, unsigned long rr) {
    const char* tag;

    if (bpm > 100.0f) {
        tag = "TACHYCARDIA";
    } else if (bpm < 60.0f) {
        tag = "BRADYCARDIA";
    } else {
        tag = "NORMAL";
    }

    // Beat-to-beat irregularity check (compared with the previous RR).
    bool irregular = false;
    if (lastRR_ms > 0) {
        float drr = fabsf((float)rr - (float)lastRR_ms) / (float)lastRR_ms;
        if (drr > 0.20f) {
            irregular = true;
        }
    }

    Serial.print(F("# BEAT BPM="));
    Serial.print(bpm, 1);
    Serial.print(F(" RR="));
    Serial.print(rr);
    Serial.print(F("ms STATUS="));
    Serial.print(tag);
    if (irregular) Serial.print(F("+IRREGULAR"));
    Serial.println();
}
